import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, Bell, Bot, CheckCircle2, ChevronDown, ChevronRight, CircleHelp, Clock3, FileText, Filter, LayoutDashboard, LogOut, Menu, Plus, Search, Settings, Sparkles, Ticket, Users, Wrench, X } from 'lucide-react';
import { api, clearSession, getSession, setSession } from './api';
import './styles.css';

const priorityClass = priority => `priority ${priority.toLowerCase()}`;
const statusClass = status => `status ${status.toLowerCase().replace(' ', '-')}`;
const relativeTime = date => date ? new Intl.RelativeTimeFormat('en', { numeric: 'auto' }).format(Math.round((new Date(date) - Date.now()) / 60000), 'minute') : 'Just now';

function App() { const [session, setAuth] = useState(getSession()); return session ? <Workspace session={session} onLogout={() => { clearSession(); setAuth(null); }} /> : <Login onSuccess={next => { setSession(next); setAuth(next); }} />; }
function Login({ onSuccess }) { const [email, setEmail] = useState('admin@smartdesk.ai'); const [password, setPassword] = useState('SmartDesk123!'); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); async function submit(e) { e.preventDefault(); setLoading(true); setError(''); try { onSuccess(await api('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) })); } catch (err) { setError(err.message); } finally { setLoading(false); } } return <div className="login-page"><div className="login-card"><div className="login-brand"><span className="brand-mark"><Sparkles size={21} /></span><span>SmartDesk <b>AI</b></span></div><p className="modal-kicker">WELCOME BACK</p><h1>Sign in to your workspace</h1><p className="login-subtitle">Manage every support request in one place.</p><form onSubmit={submit}><label>Work email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <p className="form-error">{error}</p>}<button className="primary login-submit" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'}<ChevronRight size={17} /></button></form><p className="demo-copy">Demo: <button type="button" onClick={() => { setEmail('admin@smartdesk.ai'); setPassword('SmartDesk123!'); }}>Admin</button> · <button type="button" onClick={() => { setEmail('priya@smartdesk.ai'); setPassword('SmartDesk123!'); }}>Employee</button></p></div></div>; }

function Workspace({ session, onLogout }) {
  const [tickets, setTickets] = useState([]); const [dashboard, setDashboard] = useState(null); const [section, setSection] = useState('Dashboard'); const [showCreate, setShowCreate] = useState(false); const [selected, setSelected] = useState(null); const [query, setQuery] = useState(''); const [toast, setToast] = useState(''); const [mobileNav, setMobileNav] = useState(false); const [loading, setLoading] = useState(true);
  const notify = message => { setToast(message); setTimeout(() => setToast(''), 2800); };
  async function load() { setLoading(true); try { const [ticketData, dashboardData] = await Promise.all([api('/tickets'), api('/dashboard')]); setTickets(ticketData.tickets); setDashboard(dashboardData); } catch (err) { notify(err.message); if (/session|invalid|expired/i.test(err.message)) onLogout(); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => tickets.filter(t => `${t.id} ${t.title} ${t.requester} ${t.category}`.toLowerCase().includes(query.toLowerCase())), [tickets, query]);
  async function createTicket(payload) { const { ticket } = await api('/tickets', { method: 'POST', body: JSON.stringify(payload) }); setTickets(current => [ticket, ...current]); setDashboard(current => current && ({ ...current, openTickets: current.openTickets + 1 })); setShowCreate(false); notify(`${ticket.id} created and enriched with AI`); }
  async function updateStatus(ticket, status) { try { const { ticket: updated } = await api(`/tickets/${ticket.id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); setTickets(current => current.map(t => t.id === updated.id ? updated : t)); setSelected(updated); notify(`${updated.id} marked ${status}`); } catch (err) { notify(err.message); } }
  const nav = [['Dashboard', LayoutDashboard], ['All Tickets', Ticket], ['My Queue', Wrench], ['Team Members', Users], ['Reports', Activity]]; const initials = session.user.name.split(' ').map(x => x[0]).join('').slice(0, 2);
  return <div className="app-shell"><aside className={`sidebar ${mobileNav ? 'open' : ''}`}><div className="brand"><span className="brand-mark"><Sparkles size={18} /></span><span>SmartDesk <b>AI</b></span><button className="close-nav" onClick={() => setMobileNav(false)}><X /></button></div><div className="workspace"><span className="avatar">CAE</span><div><b>Ctrl+Alt+Elite</b><small>Enterprise workspace</small></div><ChevronDown size={16} /></div><nav>{nav.map(([label, Icon]) => <button key={label} className={section === label ? 'active' : ''} onClick={() => { setSection(label); setMobileNav(false); }}><Icon size={19} />{label}{label === 'My Queue' && <em>{tickets.filter(t => !['Resolved', 'Closed'].includes(t.status)).length}</em>}</button>)}</nav><div className="nav-label">WORKSPACE</div><nav><button><CircleHelp size={19} />Knowledge Base</button><button><Settings size={19} />Settings</button></nav><div className="profile"><span className="avatar purple">{initials}</span><div><b>{session.user.name}</b><small>{session.user.role === 'admin' ? 'Administrator' : 'Employee'}</small></div><button className="logout" title="Sign out" onClick={onLogout}><LogOut size={17} /></button></div></aside><main><header><button className="menu-btn" onClick={() => setMobileNav(true)}><Menu /></button><div className="crumb"><span>Workspace</span><ChevronRight size={15} /><b>{section}</b></div><div className="header-actions"><button className="icon-btn"><Bell size={19} /><i /></button><button className="help"><CircleHelp size={19} /> Help</button><button className="primary" onClick={() => setShowCreate(true)}><Plus size={18} /> New ticket</button></div></header><section className="content"><div className="page-title"><div><p className="eyebrow">GOOD MORNING, {session.user.name.split(' ')[0].toUpperCase()}</p><h1>{section === 'Dashboard' ? 'Here’s what needs your attention.' : section}</h1><p className="subtitle">Keep your support team moving with clarity and confidence.</p></div><div className="date"><Clock3 size={17} /> {new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date())}</div></div>{loading ? <div className="page-loading"><Sparkles /> Loading your workspace…</div> : section === 'Dashboard' ? <Dashboard dashboard={dashboard} tickets={filtered} onTicket={setSelected} onCreate={() => setShowCreate(true)} /> : <TicketsPage tickets={filtered} query={query} setQuery={setQuery} onTicket={setSelected} />}</section></main>{showCreate && <CreateTicket onClose={() => setShowCreate(false)} onCreate={createTicket} />} {selected && <TicketDetails ticket={selected} admin={session.user.role === 'admin'} onClose={() => setSelected(null)} onStatus={updateStatus} />} {toast && <div className="toast"><CheckCircle2 size={18} />{toast}</div>}</div>;
}
function Dashboard({ dashboard, tickets, onTicket, onCreate }) { return <><div className="metrics"><Metric icon={<Ticket />} label="Open tickets" value={dashboard?.openTickets ?? 0} note="Active support requests" tone="blue" /><Metric icon={<Sparkles />} label="High priority" value={dashboard?.highPriority ?? 0} note="Needs attention" tone="rose" /><Metric icon={<Clock3 />} label="Avg. response time" value="18m" note="Based on recent tickets" tone="amber" /><Metric icon={<CheckCircle2 />} label="Resolved today" value={dashboard?.resolvedToday ?? 0} note="Successfully completed" tone="green" /></div><div className="dashboard-grid"><div className="panel tickets-panel"><div className="panel-head"><div><h2>Recent tickets</h2><p>Your latest support requests</p></div></div><TicketTable tickets={tickets.slice(0, 5)} onTicket={onTicket} /></div><div className="right-stack"><div className="ai-card"><div className="ai-icon"><Bot size={22} /></div><span className="pill"><Sparkles size={12} /> AI POWERED</span><h2>Let AI handle the busywork.</h2><p>Describe an issue in your own words. We’ll create the title, priority, category and route it to the right team.</p><button onClick={onCreate}>Create with AI <ChevronRight size={16} /></button></div></div></div><div className="quick-row"><div><h2>Quick actions</h2><p>Jump straight into what you need.</p></div><div className="quick-actions"><button onClick={onCreate}><span><Plus /></span>Create ticket</button><button><span><FileText /></span>Browse knowledge base</button></div></div></>; }
function Metric({ icon, label, value, note, tone }) { return <div className="metric"><span className={`metric-icon ${tone}`}>{icon}</span><div><p>{label}</p><h2>{value}</h2><small>{note}</small></div></div>; }
function TicketTable({ tickets, onTicket }) { return <div className="ticket-table"><div className="table-head"><span>Ticket</span><span>Priority</span><span>Status</span><span>Assigned to</span><span /></div>{tickets.length ? tickets.map(t => <button className="ticket-row" key={t.id} onClick={() => onTicket(t)}><span className="ticket-name"><b>{t.id}</b><small>{t.title}</small></span><span><i className={priorityClass(t.priority)}>{t.priority}</i></span><span><i className={statusClass(t.status)}>{t.status}</i></span><span className="assignee"><span className="avatar tiny">{t.team.split(' ').map(x => x[0]).join('').slice(0, 2)}</span>{t.team}</span><ChevronRight size={16} /></button>) : <p className="empty-state">No tickets found.</p>}</div>; }
function TicketsPage({ tickets, query, setQuery, onTicket }) { return <div className="panel all-tickets"><div className="toolbar"><div className="search"><Search size={18} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search tickets, people or categories" /></div><button className="filter"><Filter size={17} /> Filters</button></div><TicketTable tickets={tickets} onTicket={onTicket} /></div>; }
function CreateTicket({ onClose, onCreate }) { const [description, setDescription] = useState(''); const [loading, setLoading] = useState(false); const [analysis, setAnalysis] = useState(null); const [error, setError] = useState(''); async function analyze() { if (!description.trim()) return; setLoading(true); setError(''); try { setAnalysis(await api('/ai/enrich-ticket', { method: 'POST', body: JSON.stringify({ description }) })); } catch (err) { setError(err.message); } finally { setLoading(false); } } async function submit() { if (!analysis) return analyze(); setLoading(true); setError(''); try { await onCreate({ description, ...analysis }); } catch (err) { setError(err.message); } finally { setLoading(false); } } return <div className="modal-backdrop"><div className="modal create-modal"><div className="modal-head"><div><span className="modal-kicker"><Sparkles size={14} /> AI TICKET CREATION</span><h2>Create a support ticket</h2><p>Tell us what happened — AI fills in the details.</p></div><button className="icon-btn" onClick={onClose}><X /></button></div><label>What do you need help with?<textarea autoFocus value={description} onChange={e => { setDescription(e.target.value); setAnalysis(null); }} placeholder="Example: I can't connect my laptop to the office Wi-Fi since this morning..." /></label>{error && <p className="form-error">{error}</p>}{analysis && <div className="analysis"><div className="analysis-title"><Bot size={18} /><b>SmartDesk AI analysis</b><span>Ready</span></div><div className="analysis-grid"><p><small>TITLE</small>{analysis.title}</p><p><small>CATEGORY</small>{analysis.category}</p><p><small>PRIORITY</small><i className={priorityClass(analysis.priority)}>{analysis.priority}</i></p><p><small>SUGGESTED TEAM</small>{analysis.team}</p></div></div>}<div className="modal-foot"><button className="cancel" onClick={onClose}>Cancel</button><button className="primary" disabled={!description || loading} onClick={submit}>{loading ? 'Working…' : analysis ? 'Create ticket' : <><Sparkles size={17} /> Analyze with AI</>}</button></div></div></div>; }
function TicketDetails({ ticket, admin, onClose, onStatus }) { return <div className="modal-backdrop"><div className="modal details"><div className="modal-head"><div><span className="modal-kicker">{ticket.id}</span><h2>{ticket.title}</h2><div className="chip-row"><i className={priorityClass(ticket.priority)}>{ticket.priority}</i><i className={statusClass(ticket.status)}>{ticket.status}</i></div></div><button className="icon-btn" onClick={onClose}><X /></button></div><div className="detail-body"><section><h3>AI summary</h3><p>{ticket.summary}</p><div className="recommendation"><Sparkles size={17} /><div><b>Suggested next step</b><p>{ticket.suggestedSolution || 'Review the knowledge base and verify the affected device and account settings.'}</p></div></div><h3>Ticket activity</h3><div className="history"><div><span /><p><b>Ticket created</b><small>{relativeTime(ticket.createdAt)}</small></p></div><div><span /><p><b>Routed to {ticket.team}</b><small>AI-assisted assignment</small></p></div><div><span /><p><b>Status: {ticket.status}</b><small>Last updated {relativeTime(ticket.updatedAt)}</small></p></div></div></section><aside><h3>Details</h3><dl><dt>Requester</dt><dd>{ticket.requester}</dd><dt>Department</dt><dd>{ticket.department}</dd><dt>Category</dt><dd>{ticket.category}</dd><dt>Assigned team</dt><dd>{ticket.team}</dd></dl>{admin && <div className="status-actions"><button onClick={() => onStatus(ticket, 'In Progress')}>Start work</button><button className="resolve" onClick={() => onStatus(ticket, 'Resolved')}>Resolve ticket</button></div>}</aside></div></div></div>; }
createRoot(document.getElementById('root')).render(<App />);
